- name: "new"
  service: "@myService"
  method: "method_name"
  flags:
    - type: "string"
      name: "type"
      default: "core"
      description: "type of new project [core, desktop:console]"
    - type: "string"
      name: "name"
      default: "App"
      description: "name of the new project"
    - type: "string"
      name: "path"
      default: "./"
      description: "path to new project"

- name: "build"
  service: "@myService"
  method: "method_name"
  flags:
    - type: "string"
      name: "path"
      default: "./"
      description: "path to project to build"
